# Generated by Django 5.2.8 on 2025-12-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ví dụ: CNTT, TOAN, VAN...', max_length=20, unique=True, verbose_name='Mã khoa')),
                ('name', models.CharField(help_text='Ví dụ: Khoa Công nghệ Thông tin', max_length=255, verbose_name='Tên khoa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Danh mục khoa',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('year_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True, verbose_name='Giới tính')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Lớp')),
                ('major', models.CharField(blank=True, max_length=150, verbose_name='Ngành')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/avatars/', verbose_name='Ảnh đại diện')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn theo dõi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='portal.faculty', verbose_name='Khoa')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['mssv'],
            },
        ),
    ]
