# Generated by Django 5.2.8 on 2026-01-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'portal_research_field',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('SAMPLE', 'Mẫu / Prototype'), ('SOFTWARE', 'Phần mềm / Hệ thống'), ('PROCESS', 'Quy trình / Giải pháp'), ('MATERIAL', 'Tài liệu / Giáo trình'), ('PAPER', 'Bài báo khoa học')], default='SAMPLE', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='host_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table='portal_project',
        ),
        migrations.AddField(
            model_name='project',
            name='research_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.researchfield'),
        ),
    ]
