# Generated by Django 5.2.8 on 2025-12-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ví dụ: K45, K46...', max_length=20, unique=True, verbose_name='Mã khóa')),
                ('name', models.CharField(help_text='Ví dụ: Khóa 45 (2023–2027)', max_length=255, verbose_name='Tên khóa')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm bắt đầu')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Danh mục khóa học',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.course', verbose_name='Khóa học'),
        ),
    ]
