# Generated by Django 5.2.8 on 2026-01-06 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_researchfield_alter_project_options_project_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portal.lecturer')),
            ],
            options={
                'db_table': 'portal_lecturer_language',
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('lecturer', 'language'), name='uniq_lecturer_language')],
            },
        ),
    ]
