# Generated by Django 5.2.8 on 2026-01-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Ngành')),
            ],
            options={
                'verbose_name': 'Ngành',
                'verbose_name_plural': 'Ngành',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Khóa học', 'verbose_name_plural': 'Khóa học'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Khoa', 'verbose_name_plural': 'Khoa'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='code',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Khóa học'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Khoa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='portal.major', verbose_name='Ngành'),
        ),
    ]
