# Generated by Django 5.2.8 on 2026-01-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_lecturerlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='portal.lecturer')),
            ],
            options={
                'db_table': 'portal_lecturer_specialty',
                'ordering': ['specialty'],
                'constraints': [models.UniqueConstraint(fields=('lecturer', 'specialty'), name='uniq_lecturer_specialty')],
            },
        ),
    ]
