# Generated by Django 5.2.8 on 2026-01-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_lecturerspecialty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectlecturer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectstudent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectlecturer',
            constraint=models.UniqueConstraint(fields=('project', 'lecturer'), name='uq_project_lecturer'),
        ),
        migrations.AddConstraint(
            model_name='projectstudent',
            constraint=models.UniqueConstraint(fields=('project', 'student'), name='uq_project_student'),
        ),
    ]
