# Generated by Django 5.2.8 on 2026-01-06 03:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_projectlecturer_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('grading_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='council', to='portal.project')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Member', max_length=50)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.council')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council_memberships', to='portal.lecturer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('council', 'lecturer'), name='uq_council_lecturer')],
            },
        ),
    ]
