# Generated by Django 5.2.8 on 2026-01-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_council_councilmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='council',
            options={'ordering': ['-grading_date']},
        ),
        migrations.RemoveConstraint(
            model_name='councilmember',
            name='uq_council_lecturer',
        ),
        migrations.RenameField(
            model_name='council',
            old_name='name',
            new_name='council_title',
        ),
        migrations.RenameField(
            model_name='council',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='councilmember',
            old_name='score',
            new_name='component_score',
        ),
        migrations.RemoveField(
            model_name='council',
            name='code',
        ),
        migrations.RemoveField(
            model_name='council',
            name='established_date',
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='councilmember',
            constraint=models.UniqueConstraint(fields=('council', 'lecturer'), name='uq_council_member'),
        ),
    ]
