# Generated by Django 5.2.8 on 2026-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_council_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturerspecialty',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lecturerspecialty',
            name='updated_at',
        ),
    ]
